from typing import Protocol

from fastapi_app.domain.leaderboard.entities import LeaderboardEntry


class LeaderboardRepository(Protocol):
    def list_xp_board(self, limit: int) -> list[LeaderboardEntry]: ...
    def list_code_board(self, limit: int) -> list[LeaderboardEntry]: ...
    def my_xp_rank(self, user_id: int) -> int: ...
    def my_code_rank(self, user_id: int) -> int: ...
