from typing import Protocol

from fastapi_app.domain.organization.entities import Organization, OrganizationPost


class OrganizationRepository(Protocol):
    def get_by_key(self, org_key: str) -> Organization | None: ...
    def list_posts(self, org_key: str, limit: int) -> list[OrganizationPost]: ...
    def get_my_latest_request_status(self, org_key: str, user_id: int) -> str | None: ...
    def get_user_plan(self, user_id: int) -> str | None: ...
